import type { Festival, Contact, Post } from "@/types";

export const SUPPORTED_LOCALES = [
  { code: "en", label: "English" },
  { code: "hi", label: "हिंदी" },
];

export const BUSINESS_TYPES = [
  { value: "boutique", label: "Clothing & Boutique" },
  { value: "home_kitchen", label: "Home Kitchen / Tiffin" },
  { value: "salon", label: "Salon & Beauty" },
  { value: "jewellery", label: "Jewellery & Accessories" },
  { value: "electronics", label: "Electronics & Repair" },
  { value: "coaching", label: "Coaching / Tuition" },
  { value: "tiffin", label: "Tiffin Service" },
  { value: "other", label: "Other" },
];

export const MOCK_FESTIVALS: Festival[] = [
  {
    id: "navratri-2026",
    name: "Navratri",
    nameHi: "नवरात्रि",
    date: "2026-10-02",
    daysAway: 8,
    type: "regional",
    relevanceScore: 0.92,
    suggestedPosts: 3,
    postsCreated: 1,
    palette: ["#FF6B35", "#FFD700", "#8B0000"],
    businessTypes: ["boutique", "jewellery", "salon"],
  },
  {
    id: "dussehra-2026",
    name: "Dussehra",
    nameHi: "दशहरा",
    date: "2026-10-12",
    daysAway: 18,
    type: "national",
    relevanceScore: 0.85,
    suggestedPosts: 2,
    postsCreated: 0,
    palette: ["#FF4500", "#FFD700"],
    businessTypes: ["boutique", "jewellery", "home_kitchen"],
  },
  {
    id: "diwali-2026",
    name: "Diwali",
    nameHi: "दीपावली",
    date: "2026-10-30",
    daysAway: 36,
    type: "national",
    relevanceScore: 0.99,
    suggestedPosts: 5,
    postsCreated: 0,
    palette: ["#FF6B35", "#FFD700", "#8B0000"],
    businessTypes: ["boutique", "jewellery", "home_kitchen", "salon", "electronics"],
  },
  {
    id: "karva-chauth-2026",
    name: "Karva Chauth",
    nameHi: "करवा चौथ",
    date: "2026-10-20",
    daysAway: 26,
    type: "regional",
    relevanceScore: 0.78,
    suggestedPosts: 2,
    postsCreated: 0,
    palette: ["#C0392B", "#FFD700"],
    businessTypes: ["boutique", "jewellery", "salon"],
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "1",
    name: "Ritu Agarwal",
    phoneLast4: "8821",
    segment: "champion",
    lastOrderAt: "2026-09-20",
    lastContactedAt: "2026-09-22",
    orderCount: 12,
    purchaseCategories: ["ethnic_wear", "accessories"],
    optedInBroadcast: true,
  },
  {
    id: "2",
    name: "Sunita Devi",
    phoneLast4: "3345",
    segment: "loyal",
    lastOrderAt: "2026-09-10",
    lastContactedAt: "2026-09-12",
    orderCount: 5,
    purchaseCategories: ["ethnic_wear"],
    optedInBroadcast: true,
  },
  {
    id: "3",
    name: "Meena Sharma",
    phoneLast4: "7712",
    segment: "at_risk",
    lastOrderAt: "2026-08-01",
    lastContactedAt: "2026-08-03",
    orderCount: 3,
    purchaseCategories: ["western_wear"],
    optedInBroadcast: true,
  },
  {
    id: "4",
    name: "Kavita Singh",
    phoneLast4: "9981",
    segment: "new",
    lastOrderAt: "2026-09-18",
    lastContactedAt: "2026-09-18",
    orderCount: 1,
    purchaseCategories: ["accessories"],
    optedInBroadcast: false,
  },
  {
    id: "5",
    name: "Priya Verma",
    phoneLast4: "4456",
    segment: "birthday",
    lastOrderAt: "2026-09-05",
    lastContactedAt: "2026-09-06",
    orderCount: 4,
    purchaseCategories: ["ethnic_wear", "accessories"],
    hasBirthday: true,
    birthdayDate: "2026-10-05",
    optedInBroadcast: true,
  },
  {
    id: "6",
    name: "Anjali Gupta",
    phoneLast4: "2230",
    segment: "hibernating",
    lastOrderAt: "2026-06-15",
    lastContactedAt: "2026-06-17",
    orderCount: 2,
    purchaseCategories: ["ethnic_wear"],
    optedInBroadcast: true,
  },
  {
    id: "7",
    name: "Rekha Patel",
    phoneLast4: "5567",
    segment: "champion",
    lastOrderAt: "2026-09-22",
    lastContactedAt: "2026-09-23",
    orderCount: 9,
    purchaseCategories: ["ethnic_wear", "accessories"],
    optedInBroadcast: true,
  },
  {
    id: "8",
    name: "Shalini Jain",
    phoneLast4: "8899",
    segment: "loyal",
    lastOrderAt: "2026-09-14",
    lastContactedAt: "2026-09-15",
    orderCount: 6,
    purchaseCategories: ["western_wear"],
    optedInBroadcast: true,
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "p1",
    festivalName: "Navratri",
    caption: "Navratri is here! 🌟 New kurta collection just arrived. Visit us before stock runs out.",
    captionHi: "नवरात्रि आ गई! 🌟 नया kurta collection आया है। Stock खत्म होने से पहले आएं।",
    platform: "instagram",
    status: "approved",
    scheduledAt: "2026-09-25T18:00:00",
    imageColor: "#FF6B35",
  },
  {
    id: "p2",
    festivalName: "Navratri",
    caption: "Garba night ki taiyari? 💃 Grab your outfit from us — special Navratri prices only this week!",
    captionHi: "Garba night की तैयारी? 💃 हमसे लें अपना outfit — सिर्फ इस हफ्ते special Navratri prices!",
    platform: "whatsapp",
    status: "draft",
    imageColor: "#8B0000",
  },
  {
    id: "p3",
    caption: "Weekend special — buy 2 kurtis, get 1 dupatta free! 🛍️",
    captionHi: "Weekend special — 2 kurtis लें, 1 dupatta मुफ्त! 🛍️",
    platform: "instagram",
    status: "sent",
    imageColor: "#10b981",
  },
  {
    id: "p4",
    festivalName: "Dussehra",
    caption: "Dussehra collection preview is live! New arrivals in store. Come check it out ✨",
    captionHi: "Dussehra collection preview live है! New arrivals store में हैं। देखने आएं ✨",
    platform: "instagram",
    status: "draft",
    imageColor: "#FF4500",
  },
];

export const SEGMENT_COLORS: Record<string, { bg: string; text: string; label: string }> = {
  champion: { bg: "#fef3c7", text: "#92400e", label: "Champion" },
  loyal: { bg: "#d1fae5", text: "#065f46", label: "Loyal" },
  at_risk: { bg: "#fee2e2", text: "#991b1b", label: "At Risk" },
  new: { bg: "#dbeafe", text: "#1e40af", label: "New" },
  hibernating: { bg: "#f3f4f6", text: "#374151", label: "Hibernating" },
  birthday: { bg: "#fce7f3", text: "#9d174d", label: "Birthday 🎂" },
};
